openapi: 3.1.0
info:
  title: Process Builder API Schemas
  version: '1.0.0'
  description: Defines the data structure for process configuration.

components:
  schemas:
    ObjectInputBaseSchema:
      title: Base Persistence Schema
      description: Base properties for persistent objects.
      type: object
      properties:
        persistenceId_string:
          type: string
          description: Unique database ID of the object record.
      required:
        - persistenceId_string

    CategorySpecificProperties:
      title: Category Details
      properties:
        fullName:
          type: string
        fullDescription:
          type: string
        enabled:
          type: boolean
      required:
        - fullName
        - fullDescription
        - enabled

    ParameterSpecificProperties:
      title: Parameter Details
      properties:
        fullName:
          type: string
          maxLength: 255
        fullDescription:
          type: string
          maxLength: 1024
        version:
          type: string
          maxLength: 10
        criticality:
          type: string
          maxLength: 12
        token:
          type: string
          maxLength: 255
        displayName:
          type: string
          maxLength: 255
        documentsFolder:
          type: string
          maxLength: 255
        cancellationDelay:
          type: integer
        category:
          type: object
          allOf:
            - $ref: '#/components/schemas/ObjectInputBaseSchema'
      required:
        - fullName
        - fullDescription
        - version
        - criticality
        - token
        - displayName
        - documentsFolder
        - cancellationDelay
        - category

    ActionSchema:
      title: Action Schema
      description: Defines a single action (form, notification, redirection) within a step.
      type: object
      properties:
        actionType: { type: string }
        added: { type: boolean }
        content:
          type: array
          items: {}
      required:
        - actionType
        - added
        - content

    StepSchema:
      title: Step Schema
      description: Defines the structure for a single process step.
      type: object
      properties:
        name: { type: string }
        ref: { type: string }
        description: { type: string, description: "Detailed description of the process step." }
        index: { type: integer }
        actions:
          type: array
          items:
            $ref: '#/components/schemas/ActionSchema'
      required:
        - name
        - ref
        - description
        - index
        - actions

    StepsSpecificProperties:
      title: Process Steps List
      type: object
      properties:
        steps:
          type: array
          description: Array containing all process steps.
          items:
            $ref: '#/components/schemas/StepSchema'
      required:
        - steps
      additionalProperties: false

    Category:
      title: Category Schema
      description: Final schema structure for a category.
      type: object
      allOf:
        - $ref: '#/components/schemas/ObjectInputBaseSchema'
        - $ref: '#/components/schemas/CategorySpecificProperties'
      additionalProperties: false

    Parameter:
      title: Parameter Schema
      description: Final schema structure for parameters.
      type: object
      allOf:
        - $ref: '#/components/schemas/ObjectInputBaseSchema'
        - $ref: '#/components/schemas/ParameterSpecificProperties'
      additionalProperties: false

    Inputs:
      title: Inputs Schema
      description: Final schema structure for the process inputs.
      type: object
      allOf:
        - $ref: '#/components/schemas/ObjectInputBaseSchema'
      additionalProperties: true

    Status:
      title: Status Schema
      description: Final schema structure for statuses.
      type: object
      allOf:
        - $ref: '#/components/schemas/ObjectInputBaseSchema'
      additionalProperties: true

    Steps:
      title: Steps Schema
      description: Final schema structure for the steps collection.
      type: object
      allOf:
        - $ref: '#/components/schemas/ObjectInputBaseSchema'
        - $ref: '#/components/schemas/StepsSpecificProperties'
      additionalProperties: false

    Users:
      title: Users Schema
      description: Final schema structure for users.
      type: object
      allOf:
        - $ref: '#/components/schemas/ObjectInputBaseSchema'
      additionalProperties: true