package com.bonitasoft.processbuilder.constants;

import net.jqwik.api.*;
import net.jqwik.api.constraints.*;

import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;

import static org.assertj.core.api.Assertions.*;

/**
 * Property-based tests for {@link Constants} utility class.
 * Tests invariants that must hold for constant values.
 *
 * @author Bonitasoft
 * @since 1.0
 */
@Label("Constants Property-Based Tests")
class ConstantsPropertyTest {

    // =========================================================================
    // Constant Value Invariants
    // =========================================================================

    @Example
    @Label("TEST constant should be non-null and immutable")
    void testConstant_shouldBeNonNullAndImmutable() {
        assertThat(Constants.TEST).isNotNull();
        assertThat(Constants.TEST).isEqualTo("Test");

        // Verify it's the same reference every time (immutable)
        String ref1 = Constants.TEST;
        String ref2 = Constants.TEST;
        assertThat(ref1).isSameAs(ref2);
    }

    @Example
    @Label("EMPTY constant should be empty string")
    void emptyConstant_shouldBeEmptyString() {
        assertThat(Constants.EMPTY).isNotNull();
        assertThat(Constants.EMPTY).isEmpty();
        assertThat(Constants.EMPTY).isEqualTo("");
        assertThat(Constants.EMPTY.length()).isZero();
    }

    @Example
    @Label("Profile constants should be non-null and non-empty")
    void profileConstants_shouldBeNonNullAndNonEmpty() {
        assertThat(Constants.PB_USER_PROFILE).isNotNull().isNotEmpty();
        assertThat(Constants.PB_ADMINISTRATOR_PROFILE).isNotNull().isNotEmpty();
        assertThat(Constants.PB_PROCESS_MANAGER_PROFILE).isNotNull().isNotEmpty();
    }

    @Example
    @Label("Profile constants should contain 'PB' prefix")
    void profileConstants_shouldContainPBPrefix() {
        assertThat(Constants.PB_USER_PROFILE).startsWith("PB");
        assertThat(Constants.PB_ADMINISTRATOR_PROFILE).startsWith("PB");
        assertThat(Constants.PB_PROCESS_MANAGER_PROFILE).startsWith("PB");
    }

    @Example
    @Label("All profile constants should be unique")
    void profileConstants_shouldBeUnique() {
        assertThat(Constants.PB_USER_PROFILE)
                .isNotEqualTo(Constants.PB_ADMINISTRATOR_PROFILE)
                .isNotEqualTo(Constants.PB_PROCESS_MANAGER_PROFILE);

        assertThat(Constants.PB_ADMINISTRATOR_PROFILE)
                .isNotEqualTo(Constants.PB_PROCESS_MANAGER_PROFILE);
    }

    // =========================================================================
    // Field Modifier Invariants
    // =========================================================================

    @Example
    @Label("All constant fields should be public static final")
    void constantFields_shouldBePublicStaticFinal() {
        Field[] fields = Constants.class.getDeclaredFields();

        for (Field field : fields) {
            // Skip synthetic fields (generated by compiler)
            if (field.isSynthetic()) {
                continue;
            }

            int modifiers = field.getModifiers();
            assertThat(Modifier.isPublic(modifiers))
                    .as("Field %s should be public", field.getName())
                    .isTrue();
            assertThat(Modifier.isStatic(modifiers))
                    .as("Field %s should be static", field.getName())
                    .isTrue();
            assertThat(Modifier.isFinal(modifiers))
                    .as("Field %s should be final", field.getName())
                    .isTrue();
        }
    }

    @Example
    @Label("Class should be final to prevent inheritance")
    void class_shouldBeFinal() {
        assertThat(Modifier.isFinal(Constants.class.getModifiers())).isTrue();
    }

    @Example
    @Label("Constructor should be private")
    void constructor_shouldBePrivate() throws Exception {
        Constructor<Constants> constructor = Constants.class.getDeclaredConstructor();
        assertThat(Modifier.isPrivate(constructor.getModifiers())).isTrue();
    }

    // =========================================================================
    // String Constant Properties
    // =========================================================================

    @Property(tries = 100)
    @Label("EMPTY constant should work correctly with string concatenation")
    void emptyConstant_shouldWorkWithConcatenation(
            @ForAll @AlphaChars @StringLength(min = 1, max = 50) String input) {

        // Concatenating with EMPTY should not change the string
        String result = Constants.EMPTY + input;
        assertThat(result).isEqualTo(input);

        result = input + Constants.EMPTY;
        assertThat(result).isEqualTo(input);
    }

    @Property(tries = 100)
    @Label("TEST constant should be usable for test class name suffix detection")
    void testConstant_shouldBeUsableForTestDetection(
            @ForAll @AlphaChars @StringLength(min = 3, max = 30) String className) {

        String testClassName = className + Constants.TEST;
        assertThat(testClassName).endsWith(Constants.TEST);

        // Removing TEST suffix should give original name
        String originalName = testClassName.replace(Constants.TEST, "");
        assertThat(originalName).isEqualTo(className);
    }

    // =========================================================================
    // Consistency Properties
    // =========================================================================

    @Example
    @Label("Constants should be deterministic across multiple accesses")
    void constants_shouldBeDeterministic() {
        for (int i = 0; i < 10; i++) {
            assertThat(Constants.TEST).isEqualTo("Test");
            assertThat(Constants.EMPTY).isEqualTo("");
            assertThat(Constants.PB_USER_PROFILE).isEqualTo("PB User");
            assertThat(Constants.PB_ADMINISTRATOR_PROFILE).isEqualTo("PB Administrator");
            assertThat(Constants.PB_PROCESS_MANAGER_PROFILE).isEqualTo("PB Process Manager");
        }
    }
}
