package com.bonitasoft.processbuilder.constants;

import net.jqwik.api.*;
import net.jqwik.api.constraints.*;

import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;

import static org.assertj.core.api.Assertions.*;

/**
 * Property-based tests for {@link SchemaConstants} utility class.
 * Tests invariants that must hold for schema-related constant values.
 *
 * @author Bonitasoft
 * @since 1.0
 */
@Label("SchemaConstants Property-Based Tests")
class SchemaConstantsPropertyTest {

    // =========================================================================
    // Constant Value Invariants
    // =========================================================================

    @Example
    @Label("OPENAPI_RESOURCE_PATH should be valid resource path")
    void openApiResourcePath_shouldBeValidResourcePath() {
        assertThat(SchemaConstants.OPENAPI_RESOURCE_PATH).isNotNull();
        assertThat(SchemaConstants.OPENAPI_RESOURCE_PATH).isNotEmpty();
        assertThat(SchemaConstants.OPENAPI_RESOURCE_PATH).contains("/");
        assertThat(SchemaConstants.OPENAPI_RESOURCE_PATH).endsWith(".yaml");
        assertThat(SchemaConstants.OPENAPI_RESOURCE_PATH).doesNotStartWith("/"); // Relative path
    }

    @Example
    @Label("SCHEMA_COMPONENTS_PREFIX should be valid JSON pointer prefix")
    void schemaComponentsPrefix_shouldBeValidJsonPointerPrefix() {
        assertThat(SchemaConstants.SCHEMA_COMPONENTS_PREFIX).isNotNull();
        assertThat(SchemaConstants.SCHEMA_COMPONENTS_PREFIX).isNotEmpty();
        assertThat(SchemaConstants.SCHEMA_COMPONENTS_PREFIX).startsWith("#/");
        assertThat(SchemaConstants.SCHEMA_COMPONENTS_PREFIX).contains("components");
        assertThat(SchemaConstants.SCHEMA_COMPONENTS_PREFIX).contains("schemas");
        assertThat(SchemaConstants.SCHEMA_COMPONENTS_PREFIX).endsWith("/");
    }

    @Example
    @Label("DELETE_BASE_SCHEMA should be valid schema name")
    void deleteBaseSchema_shouldBeValidSchemaName() {
        assertThat(SchemaConstants.DELETE_BASE_SCHEMA).isNotNull();
        assertThat(SchemaConstants.DELETE_BASE_SCHEMA).isNotEmpty();
        assertThat(SchemaConstants.DELETE_BASE_SCHEMA).doesNotContain(" ");
        assertThat(SchemaConstants.DELETE_BASE_SCHEMA).doesNotContain("/");
        // Should be PascalCase
        assertThat(Character.isUpperCase(SchemaConstants.DELETE_BASE_SCHEMA.charAt(0))).isTrue();
    }

    // =========================================================================
    // Field Modifier Invariants
    // =========================================================================

    @Example
    @Label("All constant fields should be public static final")
    void constantFields_shouldBePublicStaticFinal() {
        Field[] fields = SchemaConstants.class.getDeclaredFields();

        for (Field field : fields) {
            // Skip synthetic fields (generated by compiler)
            if (field.isSynthetic()) {
                continue;
            }

            int modifiers = field.getModifiers();
            assertThat(Modifier.isPublic(modifiers))
                    .as("Field %s should be public", field.getName())
                    .isTrue();
            assertThat(Modifier.isStatic(modifiers))
                    .as("Field %s should be static", field.getName())
                    .isTrue();
            assertThat(Modifier.isFinal(modifiers))
                    .as("Field %s should be final", field.getName())
                    .isTrue();
        }
    }

    @Example
    @Label("Class should be final to prevent inheritance")
    void class_shouldBeFinal() {
        assertThat(Modifier.isFinal(SchemaConstants.class.getModifiers())).isTrue();
    }

    @Example
    @Label("Constructor should be private")
    void constructor_shouldBePrivate() throws Exception {
        Constructor<SchemaConstants> constructor = SchemaConstants.class.getDeclaredConstructor();
        assertThat(Modifier.isPrivate(constructor.getModifiers())).isTrue();
    }

    // =========================================================================
    // Schema Reference Building Properties
    // =========================================================================

    @Property(tries = 100)
    @Label("SCHEMA_COMPONENTS_PREFIX should create valid schema references")
    void schemaComponentsPrefix_shouldCreateValidSchemaReferences(
            @ForAll @AlphaChars @StringLength(min = 1, max = 30) String schemaName) {

        String schemaRef = SchemaConstants.SCHEMA_COMPONENTS_PREFIX + schemaName;

        assertThat(schemaRef).startsWith("#/components/schemas/");
        assertThat(schemaRef).endsWith(schemaName);
        assertThat(schemaRef).contains(schemaName);
    }

    @Example
    @Label("DELETE_BASE_SCHEMA should create valid reference when combined with prefix")
    void deleteBaseSchema_shouldCreateValidReferenceWithPrefix() {
        String fullRef = SchemaConstants.SCHEMA_COMPONENTS_PREFIX + SchemaConstants.DELETE_BASE_SCHEMA;

        assertThat(fullRef).isEqualTo("#/components/schemas/ObjectInputBaseSchema");
        assertThat(fullRef).startsWith("#/");
        assertThat(fullRef).contains("ObjectInputBaseSchema");
    }

    // =========================================================================
    // Path Validation Properties
    // =========================================================================

    @Example
    @Label("OPENAPI_RESOURCE_PATH should have valid file extension")
    void openApiResourcePath_shouldHaveValidExtension() {
        String path = SchemaConstants.OPENAPI_RESOURCE_PATH;

        // Should be YAML file
        assertThat(path.endsWith(".yaml") || path.endsWith(".yml")).isTrue();
    }

    @Example
    @Label("OPENAPI_RESOURCE_PATH should be in schemas directory")
    void openApiResourcePath_shouldBeInSchemasDirectory() {
        assertThat(SchemaConstants.OPENAPI_RESOURCE_PATH).startsWith("schemas/");
    }

    // =========================================================================
    // Consistency Properties
    // =========================================================================

    @Example
    @Label("Constants should be deterministic across multiple accesses")
    void constants_shouldBeDeterministic() {
        for (int i = 0; i < 10; i++) {
            assertThat(SchemaConstants.OPENAPI_RESOURCE_PATH).isEqualTo("schemas/openapi.yaml");
            assertThat(SchemaConstants.SCHEMA_COMPONENTS_PREFIX).isEqualTo("#/components/schemas/");
            assertThat(SchemaConstants.DELETE_BASE_SCHEMA).isEqualTo("ObjectInputBaseSchema");
        }
    }

    @Example
    @Label("All constants should be immutable string references")
    void constants_shouldBeImmutableReferences() {
        String ref1 = SchemaConstants.OPENAPI_RESOURCE_PATH;
        String ref2 = SchemaConstants.OPENAPI_RESOURCE_PATH;
        assertThat(ref1).isSameAs(ref2);

        ref1 = SchemaConstants.SCHEMA_COMPONENTS_PREFIX;
        ref2 = SchemaConstants.SCHEMA_COMPONENTS_PREFIX;
        assertThat(ref1).isSameAs(ref2);

        ref1 = SchemaConstants.DELETE_BASE_SCHEMA;
        ref2 = SchemaConstants.DELETE_BASE_SCHEMA;
        assertThat(ref1).isSameAs(ref2);
    }
}
